### ISSUE TITLE
don't use env vars for secrets

### ISSUE THREAD

**Issue by xenoterracide** [raulanatol/aws-s3-js-action#6]
secrets should be inputs, or maybe you can rely on the official aws credentials login to be done first? e.g.

```yml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
```

honestly inputs should probably be done for this whole thing
